spring:
    messages:
      basename: messages

server:
    port: 8080

eureka:
    instance:
        hostname: todo-service-registry
        prefer-ip-address: true
    client:
        service-url:
            default-zone: ${EUREKA_SERVER:http://localhost:8761/eureka}
        fetchRegistry: true

feign:
    client:
        config:
            default:
                connectTimeout: 160000000
                readTimeout: 160000000

ribbon:
    ConnectTimeout: 120000
    ReadTimeout: 120000

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000