spring:
  application:
    name: todo-application
  messages:
    basename: messages
  h2:
    console:
      enabled: true
server:
  port: 8080
eureka:
  client:
    service-url:
      default-zone: localhost:8761
    fetchRegistry: true