spring:
  messages:
    basename: messages
  zipkin:
    baseUrl: http://zipkin-server:9411
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://todo-service-registry:8761/eureka
feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000
ribbon:
  ConnectTimeout: 120000
  ReadTimeout: 120000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
management:
  endpoints:
    web:
      exposure:
        include: "*"