spring:
  application:
    name: Todo Application
  messages:
    basename: messages
  h2:
    console:
      enabled: true
server:
  port: 8080

product-service:
  ribbon:
    listOfServers: http://localhost:8081, http://localhost:8082